### ISSUE TITLE
Errors when compiling in IDE

### ISSUE THREAD

**Issue by HElyooo2** [KaosSpectrum/KaosGameFramework#3]
I wanted to look at this plugin and when I added it to a project and compiled it I got these errors. I fixed them on my project by adding Categories but I don't know what name you want to use. Additional infos: I use Ubuntu and cloned this project directly in UnrealEngine5/Engine/Plugins/GASUtilites/ , added it to my project through the editor and I restarted it it asked to recompile in the IDE, that's what I did and that's when I got these errors. The project in question is the GASDocummentation from Tranek, that's been updated to 5.3. I tried with a new blank 3rd person shooter project and run into the same issue.

```
0>KaosUtilitiesTypes.h(28): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>Total of 0 written
0>KaosTargetingFilterTask_IsInsideCone.h(32): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>KaosUtilitiesTypes.h(32): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>KaosUtilitiesTypes.h(36): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>KaosUtilitiesTypes.h(53): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>KaosUtilitiesTypes.h(57): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
0>KaosUtilitiesTypes.h(73): Error  : An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.


```

**Comment by KaosSpectrum** [comment]
Will take a look into it, and work out why this happening.

**Comment by KaosSpectrum** [comment]
The plugin was not built to go inside Engine/Plugins but instead YourProject/Plugins.

**Comment by KaosSpectrum** [comment]
Should be fixed in the new commit :)
