### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by glimpsebeyond** [KaosSpectrum/KaosGameFramework#4]
I'd like to use some of this code but without a license all rights are reserved.

**Comment by KaosSpectrum** [comment]
As long as you don't remove the copyright notice, sure.

**Comment by glimpsebeyond** [comment]
What I mean is unless you choose a license nobody can use this code, regardless of what is said here. If you've released this on the marketplace then it would at least have that license. For my purpose I can't use this at all without commercial rights.

**Comment by KaosSpectrum** [comment]
I see, yeah i never updated the headers, its using the old one, i will get this updated when i get a chance.

**Comment by KaosSpectrum** [comment]
Licence updated, should be good now :) Ill drop Licence file in also

**Comment by glimpsebeyond** [comment]
MIT is what I like to see. Thanks!
