### ISSUE TITLE
This is fantastic thank you!

### ISSUE THREAD

**Issue by tdhavema** [KaosSpectrum/KaosGameFramework#5]
Hey I just want to say I really appreciate these. I don't fully understand how they all work yet, but the few I have tried work perfectly. 

There's only one thing I want to mention, and that's I'm on 5.4.1 and when my Rider went to compile the first time after adding these files, it gave me an error for 2 enums and said that only uint8 was supported currently.

They are in KaosBTService_ActivateAbilityByTag.h declaring enum EKaosActivateAbilityByTagOnCeaseRelevanceBehaviour I had to add 
: uint8
As well as in KaosBTTask_ExecuteGameplayAbility.h declaring enum EKaosExecuteGameplayAbilityAbortBehaviour I had to add : uint8

I have no idea if that means much, but it was just a compile issue when I first added the files.

**Comment by KaosSpectrum** [comment]
I pushed a fix for it, same as what you did. Thanks for letting me know :)
